-- Import nội dung từ https://nhakhoagiakiem.com/
update settings set
  hotline = '0985263661',
  address = '134/5 Bạch Lâm 1, Xã Thống Nhất, tỉnh Đồng Nai',
  meta_title = 'Nha Khoa Uy Đức - Nha khoa uy tín khu vực Gia Kiệm',
  meta_description = 'Nha Khoa Uy Đức Smile cung cấp dịch vụ nha khoa uy tín tại Gia Kiệm, Đồng Nai với đội ngũ tận tâm và dịch vụ chăm sóc nụ cười toàn diện',
  about_title = 'Nha Khoa Uy Đức Smile - Nha khoa uy tín khu vực Gia Kiệm',
  about_description_1 = 'Nha Khoa Uy Đức Smile đồng hành cùng khách hàng trong chăm sóc, điều trị và cải thiện thẩm mỹ nụ cười.',
  about_description_2 = 'Phòng khám chú trọng tư vấn rõ ràng, thăm khám kỹ lưỡng và lựa chọn phương án phù hợp với từng tình trạng răng miệng.',
  about_description_3 = 'Các dịch vụ nổi bật gồm răng sứ thẩm mỹ, trồng răng Implant, niềng răng, tẩy trắng răng, nhổ răng khôn và trám răng thẩm mỹ.',
  about_image_url = 'https://nhakhoagiakiem.com/thumbs/661x378x1/upload/news/nhakhoaresizedv2-1523.png'
where id = 1;
truncate table banners restart identity cascade;
truncate table services restart identity cascade;
truncate table posts restart identity cascade;
insert into banners (title, subtitle, image_url, cta_text, sort_order) values
('NHA KHOA UY ĐỨC SMILE', 'Nha khoa uy tín khu vực Gia Kiệm - Đồng Nai', 'https://nhakhoagiakiem.com/thumbs/1366x550x1/upload/photo/nhakhoagiakiem-slider-1-20350.png', 'ĐẶT HẸN NGAY', 1),
('CHĂM SÓC NỤ CƯỜI TOÀN DIỆN', 'Dịch vụ nha khoa hiện đại, tận tâm và an toàn', 'https://nhakhoagiakiem.com/thumbs/1366x550x1/upload/photo/nhakhoagiakiem-slider-2-71250.png', 'Tư vấn miễn phí', 2);
insert into services (name, description, image_url) values
('Răng sứ thẩm mỹ', 'Phục hình răng sứ thẩm mỹ, cải thiện màu sắc và dáng răng tự nhiên.', 'https://nhakhoagiakiem.com/thumbs/340x270x1/upload/news/rang-su-2-9204.jpg'),
('Trồng răng Implant', 'Giải pháp phục hồi răng mất bền vững, hỗ trợ ăn nhai chắc chắn.', 'https://nhakhoagiakiem.com/thumbs/340x270x1/upload/news/rang-su-2796.jpg'),
('Tẩy trắng răng', 'Giúp răng sáng khỏe, cải thiện thẩm mỹ nụ cười nhanh chóng.', 'https://nhakhoagiakiem.com/thumbs/340x270x1/upload/news/voi-rang-2761.jpg'),
('Nhổ răng khôn', 'Thăm khám kỹ lưỡng, xử lý răng khôn an toàn và giảm đau.', 'https://nhakhoagiakiem.com/thumbs/340x270x1/upload/news/img8956-1677-3662.jpg'),
('Niềng răng', 'Cải thiện khớp cắn và thẩm mỹ nụ cười với lộ trình phù hợp.', 'https://nhakhoagiakiem.com/thumbs/340x270x1/upload/news/img8955-4068-3455.jpg'),
('Trám răng thẩm mỹ', 'Khôi phục răng sâu, mẻ hoặc thưa bằng vật liệu thẩm mỹ.', 'https://nhakhoagiakiem.com/thumbs/340x270x1/upload/news/z694275626332853d8bacf6d0730aa071448872b0c5a26-3532.jpg');
insert into posts (title, excerpt, content, image_url, category) values
('ĐÓN TẾT BÍNH NGỌ – RẠNG RỠ NỤ CƯỜI ĐÓN XUÂN', 'Tết đến là lúc ai cũng muốn chỉnh chu hơn cho nụ cười, để tự tin gặp gỡ gia đình, bạn bè và người thân ????', 'Nội dung đang được cập nhật từ Nha Khoa Uy Đức Smile. Quý khách có thể liên hệ hotline 0985263661 để được tư vấn chi tiết về dịch vụ nha khoa phù hợp.', 'https://nhakhoagiakiem.com/thumbs/1920x1920x2/upload/news/day-mau-sac-sale-deal-uu-dai-san-pham-tet-nguyen-dan-viet-nam-instagram-post-6677.png', 'Tin tức'),
('THÔNG BÁO LỊCH NGHỈ TẾT DƯƠNG LỊCH', 'Nội dung đang được cập nhật từ Nha Khoa Uy Đức Smile. Quý khách có thể liên hệ hotline 0985263661 để được tư vấn chi tiết về dịch vụ nha khoa phù hợp.', 'Nội dung đang được cập nhật từ Nha Khoa Uy Đức Smile. Quý khách có thể liên hệ hotline 0985263661 để được tư vấn chi tiết về dịch vụ nha khoa phù hợp.', 'https://nhakhoagiakiem.com/thumbs/526x526x2/upload/news/6051501531221991158385270982775264770736881457n-6859.jpg', 'Tin tức'),
('Niềng Răng Có Đau Không? Chia Sẻ Thực Tế Trước Khi Quyết Định', '???? Niềng Răng Có Đau Không? Chia Sẻ Thực Tế Trước Khi Quyết Định Rất nhiều khách khi đến Nha Khoa Uy Đức đều hỏi: ???? “Niềng răng có đau không bác sĩ?” Câu trả l', 'Nội dung đang được cập nhật từ Nha Khoa Uy Đức Smile. Quý khách có thể liên hệ hotline 0985263661 để được tư vấn chi tiết về dịch vụ nha khoa phù hợp.', 'https://nhakhoagiakiem.com/thumbs/1920x1920x2/upload/news/xanh-duong-hong-dau-rang-ro-rang-nhieu-thong-tin-suc-khoe-ve-sinh-nha-si-bai-dang-instagram-5416.png', 'Tin tức'),
('TẨY TRẮNG RĂNG GIA KIỆM ĐỒNG NAI – TỰ TIN NỤ CƯỜI SÁNG KHỎE MỖI NGÀY', 'Răng xỉn màu do cà phê, trà, thuốc lá hoặc theo thời gian khiến nhiều người ngại cười và thiếu tự tin khi giao tiếp. Tẩy trắng răng là phương pháp nha khoa giú', 'Nội dung đang được cập nhật từ Nha Khoa Uy Đức Smile. Quý khách có thể liên hệ hotline 0985263661 để được tư vấn chi tiết về dịch vụ nha khoa phù hợp.', 'https://nhakhoagiakiem.com/thumbs/512x640x2/upload/news/6048103521221981780625270985280308438413685884n-6771.jpg', 'Tin tức'),
('TRỒNG RĂNG IMPLANT – GIẢI PHÁP KHÔI PHỤC RĂNG MẤT BỀN VỮNG', 'Mất răng lâu ngày không chỉ ảnh hưởng thẩm mỹ mà còn gây tiêu xương hàm, xô lệch răng kế cận và khó khăn khi ăn nhai.', 'Nội dung đang được cập nhật từ Nha Khoa Uy Đức Smile. Quý khách có thể liên hệ hotline 0985263661 để được tư vấn chi tiết về dịch vụ nha khoa phù hợp.', 'https://nhakhoagiakiem.com/thumbs/1638x2048x2/upload/news/6001086711221977295865270989130048216879219778n-4812.jpg', 'Tin tức'),
('NHỔ RĂNG KHÔN – GIẢI PHÁP GIẢM ĐAU, BẢO VỆ RĂNG BÊN CẠNH', 'Răng khôn mọc lệch, mọc ngầm thường gây đau nhức, sưng viêm, kẹt thức ăn, thậm chí ảnh hưởng đến các răng kế bên nếu không xử lý kịp thời.', 'Nội dung đang được cập nhật từ Nha Khoa Uy Đức Smile. Quý khách có thể liên hệ hotline 0985263661 để được tư vấn chi tiết về dịch vụ nha khoa phù hợp.', 'https://nhakhoagiakiem.com/thumbs/1080x1350x2/upload/news/white-modern-dental-checkup-promotion-instagram-post-7-8890.png', 'Tin tức'),
('RĂNG THÁO LẮP – GIẢI PHÁP TIẾT KIỆM, AN TÂM CHO CÔ CHÚ', 'Mất răng khiến ăn nhai khó, nói chuyện không thoải mái và ngại giao tiếp. Răng tháo lắp là giải pháp đơn giản – dễ sử dụng – phù hợp với cô chú lớn tuổi và ngườ', 'Nội dung đang được cập nhật từ Nha Khoa Uy Đức Smile. Quý khách có thể liên hệ hotline 0985263661 để được tư vấn chi tiết về dịch vụ nha khoa phù hợp.', 'https://nhakhoagiakiem.com/thumbs/1536x1920x2/upload/news/white-modern-dental-checkup-promotion-instagram-post-5-9537.png', 'Tin tức'),
('Phục hình răng là gì?', 'Răng sứt mẻ, xỉn màu, thưa hoặc mất răng không chỉ ảnh hưởng đến ngoại hình mà còn gây khó khăn khi ăn nhai và giao tiếp. Phục hình răng là giải pháp nha khoa h', 'Nội dung đang được cập nhật từ Nha Khoa Uy Đức Smile. Quý khách có thể liên hệ hotline 0985263661 để được tư vấn chi tiết về dịch vụ nha khoa phù hợp.', 'https://nhakhoagiakiem.com/thumbs/1080x1350x2/upload/news/white-modern-dental-checkup-promotion-instagram-post-4-4345.png', 'Tin tức'),
('NIỀNG RĂNG – ĐẦU TƯ MỘT LẦN, TỰ TIN CẢ ĐỜI', 'Nội dung đang được cập nhật từ Nha Khoa Uy Đức Smile. Quý khách có thể liên hệ hotline 0985263661 để được tư vấn chi tiết về dịch vụ nha khoa phù hợp.', 'Nội dung đang được cập nhật từ Nha Khoa Uy Đức Smile. Quý khách có thể liên hệ hotline 0985263661 để được tư vấn chi tiết về dịch vụ nha khoa phù hợp.', 'https://nhakhoagiakiem.com/thumbs/1080x1350x2/upload/news/white-modern-dental-checkup-promotion-instagram-post-3-7506.png', 'Tin tức'),
('TRÁM RĂNG THẨM MỸ – GIẢI PHÁP KHÔI PHỤC RĂNG NHANH, AN TOÀN VÀ TIẾT KI', 'Trám răng là một trong những phương pháp nha khoa phổ biến và hiệu quả giúp phục hồi răng sâu, răng mẻ, sứt hoặc thẩm mỹ kém. Với công nghệ hiện đại, trám răng', 'Nội dung đang được cập nhật từ Nha Khoa Uy Đức Smile. Quý khách có thể liên hệ hotline 0985263661 để được tư vấn chi tiết về dịch vụ nha khoa phù hợp.', 'https://nhakhoagiakiem.com/thumbs/1080x1080x2/upload/news/white-and-blue-modern-dental-clinic-instagram-post-1854.png', 'Tin tức'),
('Nha Khoa Uy Đức – Nha Khoa Gia Kiệm Uy Tín, Chất Lượng Tại Đồng Nai', 'Nội dung đang được cập nhật từ Nha Khoa Uy Đức Smile. Quý khách có thể liên hệ hotline 0985263661 để được tư vấn chi tiết về dịch vụ nha khoa phù hợp.', 'Nội dung đang được cập nhật từ Nha Khoa Uy Đức Smile. Quý khách có thể liên hệ hotline 0985263661 để được tư vấn chi tiết về dịch vụ nha khoa phù hợp.', 'https://nhakhoagiakiem.com/thumbs/823x465x2/upload/news/meet-the-team-1275.png', 'Tin tức'),
('Dịch vụ bọc răng sứ thẩm mỹ uy tín nhất tại Đồng Nai', 'UY ĐỨC SMILE cung cấp dịch vụ bọc răng sứ chất lượng với đội ngũ bác sĩ có chuyên môn và kiến thức sâu rộng, áp dụng công nghệ tiên tiến, hiện đại và quá trình bọc răng', 'Nội dung đang được cập nhật từ Nha Khoa Uy Đức Smile. Quý khách có thể liên hệ hotline 0985263661 để được tư vấn chi tiết về dịch vụ nha khoa phù hợp.', 'https://nhakhoagiakiem.com/thumbs/800x500x2/upload/news/boc-rang-su-tham-my-8418.png', 'Tin tức');

